-- Migration 0014: content depth — NPC memory, seasons, world events, quest chains

-- NPC conversation memory (last 3 summaries per player-NPC pair)
CREATE TABLE IF NOT EXISTS npc_interactions (
  player_id  UUID        NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  npc_id     VARCHAR(50) NOT NULL,
  zone_id    VARCHAR(50) NOT NULL,
  -- JSON array of up to 3 interaction summaries (most recent last)
  summaries  JSONB       NOT NULL DEFAULT '[]',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (player_id, npc_id)
);

-- Seasons (active season drives LLM quest theme)
CREATE TABLE IF NOT EXISTS seasons (
  id                    UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  name                  VARCHAR(60) NOT NULL,
  start_date            DATE        NOT NULL,
  end_date              DATE        NOT NULL,
  story_prompt_template TEXT        NOT NULL DEFAULT '',
  is_active             BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS seasons_active_idx ON seasons(is_active) WHERE is_active = TRUE;

-- Insert the first two seasons (spring/summer) as seed data
INSERT INTO seasons (name, start_date, end_date, story_prompt_template, is_active)
VALUES
  ('Spring of Renewal',  '2026-03-01', '2026-05-31',
   'The world is awakening after a long winter. Ancient seeds stir beneath the earth and forgotten spirits return to the forests. Quests should feel hopeful and involve renewal, growth, and new beginnings.',
   TRUE),
  ('Summer of Conflict', '2026-06-01', '2026-08-31',
   'The summer sun blazes and old rivalries resurface. Factions vie for control of scarce resources. Quests should involve tension, competition, and moments of unlikely alliance.',
   FALSE)
ON CONFLICT DO NOTHING;

-- World events (persisted across restarts)
CREATE TABLE IF NOT EXISTS world_events (
  id          UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  zone_id     VARCHAR(50) NOT NULL,
  name        VARCHAR(100) NOT NULL,
  description TEXT         NOT NULL DEFAULT '',
  is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
  event_data  JSONB        NOT NULL DEFAULT '{}',
  starts_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  ends_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS world_events_zone_active_idx ON world_events(zone_id, is_active);

-- Quest chains (multi-step storylines generated by LLM)
CREATE TABLE IF NOT EXISTS quest_chains (
  id                   UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  zone_id              VARCHAR(50) NOT NULL,
  player_level_bucket  INTEGER     NOT NULL,
  title                VARCHAR(200) NOT NULL,
  theme                TEXT         NOT NULL DEFAULT '',
  -- JSON array of quest IDs referencing generated_quests
  quest_ids            JSONB        NOT NULL DEFAULT '[]',
  generated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  expires_at           TIMESTAMPTZ  NOT NULL
);
CREATE INDEX IF NOT EXISTS quest_chains_zone_bucket_idx ON quest_chains(zone_id, player_level_bucket);

-- Track player progress through quest chains
CREATE TABLE IF NOT EXISTS player_chain_progress (
  player_id    UUID        NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  chain_id     UUID        NOT NULL REFERENCES quest_chains(id) ON DELETE CASCADE,
  current_step INTEGER     NOT NULL DEFAULT 0,
  status       VARCHAR(20) NOT NULL DEFAULT 'active', -- 'active' | 'completed' | 'abandoned'
  started_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (player_id, chain_id)
);
