#!/usr/bin/env node
// Generate M37-M40 achievement icons (16x16 pixel art, master palette)
// Usage: node tools/generate_achievement_icons.js

const sharp = require('sharp');
const path = require('path');
const fs = require('fs');

// 32-color master palette + transparent
const PAL = {
  '.': [0, 0, 0, 0],
  'K': [13, 13, 13, 255],
  'D': [43, 43, 43, 255],
  'G': [74, 74, 74, 255],
  'M': [110, 110, 110, 255],
  'L': [150, 150, 150, 255],
  'S': [200, 200, 200, 255],
  'W': [240, 240, 240, 255],
  'b': [59, 32, 16, 255],
  'e': [107, 58, 31, 255],
  'd': [139, 92, 42, 255],
  's': [184, 132, 63, 255],
  'g': [212, 168, 90, 255],
  'p': [232, 208, 138, 255],
  'F': [26, 58, 26, 255],
  'f': [45, 110, 45, 255],
  'l': [76, 155, 76, 255],
  'h': [120, 200, 120, 255],
  'a': [168, 228, 160, 255],
  'O': [10, 26, 58, 255],
  'B': [26, 74, 138, 255],
  'C': [42, 122, 192, 255],
  'c': [80, 168, 232, 255],
  'i': [144, 208, 248, 255],
  'w': [200, 240, 255, 255],
  'R': [90, 10, 10, 255],
  'r': [160, 16, 16, 255],
  'X': [212, 32, 32, 255],
  'o': [240, 96, 32, 255],
  'E': [248, 160, 96, 255],
  'A': [168, 112, 0, 255],
  'Y': [232, 184, 0, 255],
  'y': [255, 224, 64, 255],
  'P': [255, 248, 160, 255],
  'V': [26, 10, 58, 255],
  'v': [90, 32, 160, 255],
  'm': [144, 80, 224, 255],
  'n': [208, 144, 255, 255],
};

function parseGrid(template) {
  const rows = template.trim().split('\n').map(r => r.trim());
  if (rows.length !== 16) throw new Error(`Expected 16 rows, got ${rows.length}`);
  for (let i = 0; i < 16; i++) {
    if (rows[i].length !== 16) {
      throw new Error(`Row ${i} is ${rows[i].length} chars (expected 16): "${rows[i]}"`);
    }
    for (let j = 0; j < 16; j++) {
      if (!PAL.hasOwnProperty(rows[i][j])) {
        throw new Error(`Unknown char '${rows[i][j]}' at row ${i} col ${j}`);
      }
    }
  }
  return rows;
}

function gridToBuffer(rows) {
  const buf = Buffer.alloc(16 * 16 * 4, 0);
  for (let y = 0; y < 16; y++) {
    for (let x = 0; x < 16; x++) {
      const rgba = PAL[rows[y][x]];
      if (rgba[3] === 0) continue;
      const off = (y * 16 + x) * 4;
      buf[off]     = rgba[0];
      buf[off + 1] = rgba[1];
      buf[off + 2] = rgba[2];
      buf[off + 3] = rgba[3];
    }
  }
  return buf;
}

// ================================================================
// ICON DEFINITIONS — 16x16 pixel art, master palette only
// Key: A=dark gold outline, Y=gold fill, y=bright yellow, P=pale highlight
//      e=earth brown, W=near white, D=dark gray, g=desert gold
// ================================================================

const ICONS = {

  // ======== HOUSING ========

  first_home: `
................
................
.......Y........
......YYY.......
.....YYYYY......
....YYYYYYY.....
...AAAAAAAAA....
....AeeeeeA.....
....AeWeWeA.....
....AeeeeeA.....
....AeeAeeA.....
....AeeAeeA.....
....AAAAAAA.....
................
................
................`,

  interior_designer: `
................
................
.......y........
......YyY.......
.....YYyYY......
....YYYyYYY.....
...AAAAAAAAA....
....AeeeeeA.....
....AyWyWyA.....
....AgpgpgA.....
....AeeYeeA.....
....AeeYeeA.....
....AAAAAAA.....
................
................
................`,

  landlord: `
................
.....y.y.y......
.....YYYYY......
.......Y........
......YyY.......
.....YYyYY......
....YYYyYYY.....
...AAAAAAAAA....
....AyWyWyA.....
....AeeeeeA.....
....AeYYYeA.....
....AeYYYeA.....
....AAAAAAA.....
................
................
................`,

  // ======== MOUNTS ========

  first_ride: `
................
................
................
...AY......YA...
...AY......YA...
...AY......YA...
...AY......YA...
...AYY....YYA...
....AYYYYYYA....
.....AYYYYA.....
......AYYA......
.......AA.......
................
................
................
................`,

  stable_master: `
................
................
................
...AY......YA...
...AY..y...YA...
...AY.yYy..YA...
...AY..y...YA...
...AYY....YYA...
....AYYYYYYA....
.....AYYYYA.....
......AYYA......
.......AA.......
................
................
................
................`,

  mount_collector: `
.....y.y.y......
.....YYYYY......
................
...AY......YA...
...AY..P...YA...
...AY.PYP..YA...
...AY..P...YA...
...AYY....YYA...
....AYYYYYYA....
.....AYYYYA.....
......AYYA......
.......AA.......
................
................
................
................`,

  // ======== AUCTION HOUSE ========

  first_sale: `
................
................
................
......AAAA......
.....AYYYyA.....
....AYYYYYyA....
....AYYAYYyA....
....AYYAYYyA....
....AYYYYYyA....
.....AYYYyA.....
......AAAA......
................
................
................
................
................`,

  merchant: `
................
................
.......YY.......
......AAAA......
.....AAAAAA.....
....AYYYYYYA....
...AYYYYYYYyA...
...AYYYAYYyyA...
...AYYYAYYyyA...
...AYYYYYYYyA...
....AYYYYyyA....
.....AAAAAA.....
................
................
................
................`,

  tycoon: `
................
......y.y.......
.....y.P.y......
.....AAAAAA.....
....AYYYYYYA....
....AAAAAAAA....
....AeYYYYeA....
....AeYAYYeA....
....AeYAYYeA....
....AeYYYYeA....
....AAAAAAAA....
................
................
................
................
................`,

  // ======== FISHING ========

  first_catch: `
................
................
................
.........A......
........AYA.....
..AAAAYYYYYYA...
..AYYYYYYWYYYA..
..AAAAYYYYYYA...
........AYA.....
.........A......
................
................
................
................
................
................`,

  angler: `
................
................
.............y..
.........A......
........AYA.....
..AAAAYYYYYYA...
..AYYYYYYWYYYA..
..AAAAYYYYYYA...
........AYA.....
.........A......
................
................
................
................
................
................`,

  master_fisher: `
................
........y.......
.......yYy......
........y.......
........AYA.....
..AAAAYYYYYYA...
..AYYYYYYWYYYA..
..AAAAYYYYYYA...
........AYA.....
.........A......
................
................
................
................
................
................`,

  legendary_catch: `
.P............P.
................
........P.......
.........A......
........AyA.....
..AAAAyyyyyyA...
..AyyyyyyWyyyA..
..AAAAyyyyyyA...
........AyA.....
.........A......
................
..P.............
...........P....
................
................
................`,

  // ======== BESTIARY ========

  novice_explorer: `
................
................
................
.....AAAAAAA....
....AYYYYYYYA...
....AYeYYYYYA...
....AYYYYYYYA...
....AYYYYYYYA...
....AYYYYYYYA...
....AYYYYYYYA...
.....AAAAAAA....
.....DDDDDDD....
................
................
................
................`,

  seasoned_hunter: `
................
................
................
.....AAAAAAA....
....AYYYYYYYA...
....AYeYeYYYA...
....AYYYYYYYA...
....AYeYeYYYA...
....AYYYYYYYA...
....AYYYYYYYA...
.....AAAAAAA....
.....DDDDDDD....
................
................
................
................`,

  monster_scholar: `
................
................
................
.....AAAAAAA....
....AYYYYYYYA...
....AYeYeYeYA...
....AYYYYYYYA...
....AYeYeYeYA...
....AYYYYYYYA...
....AYeYeYYYA...
.....AAAAAAA....
.....DDDDDDD....
................
................
................
................`,

  bestiary_complete: `
................
.......P........
................
.....AAAAAAA....
....AyyyyyyyA...
....AyeYeYeYA...
....AyYYYYYYA...
....AyeYeYeYA...
....AyYYYYYYA...
....AyeYeYeYA...
.....AAAAAAA....
.....DDDDDDD....
................
.......P........
................
................`,

  // ======== DODGE / COMBAT ========

  first_dodge: `
................
................
........YY......
.......YYY......
......YYYY......
.....YYYYY......
....AAAYYYY.....
.......YYYY.....
......YYYY......
.....YYYY.......
....YYYY........
...YYYY.........
..AAA...........
................
................
................`,

  perfect_dodge: `
................
............y...
........YY......
.......YYY......
......YYYY......
.....YYYYY......
....AAAYYYY.....
.......YYYY.....
......YYYY......
.....YYYY.......
....YYYY........
...YYYY.........
..AAA...........
.y..............
................
................`,

  untouchable: `
.....y.y.y......
.....YYYYY......
........yy......
.......yyy......
......yyyy......
.....yyyyy......
....AAAyyyy.....
.......yyyy.....
......yyyy......
.....yyyy.......
....yyyy........
...yyyy.........
..AAA...........
..............P.
................
................`,

  // ======== COSMETIC SHOP ========

  fashion_forward: `
................
................
................
....YYYYYYY.....
....YYYYYYY.....
....AAAAAAA.....
....YYYYYYY.....
....YYYYYYY.....
..AYYYYYYYYYA...
..AAAAAAAAAAA...
................
................
................
................
................
................`,

  style_icon: `
................
.P............P.
....y.y.y.y.....
....YyYyYyY.....
.....YYYYY......
....YYYYYYY.....
....AAAAAAA.....
....YgYgYgY.....
....YYYYYYY.....
....AAAAAAA.....
................
.P............P.
................
................
................
................`,

  // ======== WORLD MAP ========

  cartographer: `
................
................
..AAAAAAAAAA....
..AYYYYYYYYyA...
..AYYeYYeYYyA...
..AYYYYYeYYyA...
..AYYeYYYYYyA...
..AYYYYYYYYyA...
..AAAAAAAAAA....
..AA........AA..
...AA......AA...
................
................
................
................
................`,

  globe_trotter: `
................
................
.......y........
......YYY.......
......YYY.......
......YYY.......
......AYA.......
.yYYYYAYAYYYYy..
......AYA.......
......YYY.......
......YYY.......
......YYY.......
.......y........
................
................
................`,

};

// ================================================================
// GENERATION
// ================================================================

const OUT_DIR = path.resolve(__dirname, '..', 'assets', 'ui', 'icons');

async function main() {
  console.log('Generating M37-M40 achievement icons...');
  console.log(`Output: ${OUT_DIR}\n`);

  const names = Object.keys(ICONS);
  const buffers = [];

  for (const name of names) {
    const grid = parseGrid(ICONS[name]);
    const buf = gridToBuffer(grid);
    const file = path.join(OUT_DIR, `icon_achieve_${name}.png`);
    await sharp(buf, { raw: { width: 16, height: 16, channels: 4 } })
      .png()
      .toFile(file);
    console.log(`  ✓ icon_achieve_${name}.png`);
    buffers.push({ name, buf });
  }

  // Assemble sprite sheet: 8 columns × 3 rows
  const cols = 8;
  const rows = Math.ceil(names.length / cols);
  const sheetW = cols * 16;
  const sheetH = rows * 16;
  const sheetBuf = Buffer.alloc(sheetW * sheetH * 4, 0);

  for (let idx = 0; idx < buffers.length; idx++) {
    const col = idx % cols;
    const row = Math.floor(idx / cols);
    const src = buffers[idx].buf;
    for (let y = 0; y < 16; y++) {
      for (let x = 0; x < 16; x++) {
        const srcOff = (y * 16 + x) * 4;
        const dstX = col * 16 + x;
        const dstY = row * 16 + y;
        const dstOff = (dstY * sheetW + dstX) * 4;
        sheetBuf[dstOff]     = src[srcOff];
        sheetBuf[dstOff + 1] = src[srcOff + 1];
        sheetBuf[dstOff + 2] = src[srcOff + 2];
        sheetBuf[dstOff + 3] = src[srcOff + 3];
      }
    }
  }

  const sheetFile = path.join(OUT_DIR, 'icon_achieve_m37m40_sheet.png');
  await sharp(sheetBuf, { raw: { width: sheetW, height: sheetH, channels: 4 } })
    .png()
    .toFile(sheetFile);

  console.log(`\n  ✓ Sprite sheet: icon_achieve_m37m40_sheet.png (${sheetW}×${sheetH}, ${cols}×${rows} grid)`);
  console.log(`\nSprite sheet layout (left→right, top→bottom):`);
  for (let r = 0; r < rows; r++) {
    const rowNames = names.slice(r * cols, (r + 1) * cols);
    console.log(`  Row ${r}: ${rowNames.join(', ')}`);
  }

  console.log(`\nDone! ${names.length} icons + 1 sprite sheet generated.`);
}

main().catch(err => {
  console.error('ERROR:', err.message);
  process.exit(1);
});
